services:
  db:
    image: postgres:15-alpine
    container_name: my_nest_postgres
    restart: always
    environment:
      POSTGRES_USER: rootroot
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: nestdb
    ports:
      - '5433:5432'
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rootroot -d nestdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: my_nest_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: rootpassword
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data_v2:
  pgadmin_data: